# Generated by Django 4.1.4 on 2022-12-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addstudent',
            name='studentAge',
            field=models.IntegerField(),
        ),
    ]
