# Generated by Django 4.1.4 on 2022-12-06 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0004_book_rentbook_rename_studentadd_addstudent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
    ]
