# Generated by Django 4.1.4 on 2022-12-07 23:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0006_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentbook',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='rentbook',
            name='dateDue',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 18, 47, 44, 293603)),
        ),
    ]
