# Generated by Django 4.1.4 on 2022-12-08 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0007_rentbook_returned_alter_book_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='addstudent',
        ),
        migrations.AlterField(
            model_name='rentbook',
            name='dateDue',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 15, 21, 17, 29, 261865)),
        ),
    ]
