# Generated by Django 4.1.4 on 2022-12-08 03:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LibraryManagement', '0008_delete_addstudent_alter_rentbook_datedue'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rentbook',
            name='rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rentbook',
            name='dateDue',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 22, 25, 36, 431834)),
        ),
    ]
