# Generated by Django 4.1.4 on 2022-12-08 03:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0009_book_user_rentbook_rented_alter_rentbook_datedue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentbook',
            name='rented',
        ),
        migrations.RemoveField(
            model_name='rentbook',
            name='returned',
        ),
        migrations.AddField(
            model_name='book',
            name='rented',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rentbook',
            name='dateDue',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 22, 41, 36, 531237)),
        ),
    ]
