# Generated by Django 4.1.4 on 2022-12-08 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryManagement', '0010_remove_rentbook_rented_remove_rentbook_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentbook',
            name='dateDue',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 22, 17, 7, 19, 250469)),
        ),
    ]
